# Generated by Django 4.0.3 on 2022-04-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('1', 'Reparación'), ('2', 'Mantenimiento'), ('3', 'Instalación de software'), ('4', 'Otro')], default='1', max_length=1)),
                ('employee_id', models.IntegerField(default=0)),
                ('description', models.TextField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
