# Generated by Django 4.0.3 on 2022-04-16 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('RH', 'Recursos Humanos'), ('ST', 'Soporte Técnico'), ('MT', 'Mercadotecnia'), ('EB', 'Ensamblaje'), ('DT', 'Distribución'), ('AL', 'Almacén'), ('FN', 'Finanzas')], default='RH', max_length=100)),
                ('description', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default='O', max_length=1)),
                ('email', models.EmailField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('hire_date', models.DateField()),
                ('monthly_salary', models.FloatField(default=0.0)),
                ('bonus', models.FloatField(default=0.0)),
                ('contract_id', models.IntegerField()),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.department')),
            ],
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=255)),
                ('value', models.FloatField(default=0.0)),
                ('quantity', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('min_salary', models.FloatField(default=0.0)),
                ('max_salary', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('delivery_date', models.DateTimeField()),
                ('notes', models.TextField(max_length=255)),
                ('attendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('1', 'Reparación'), ('2', 'Mantenimiento'), ('3', 'Instalación de software'), ('4', 'Otro')], default='1', max_length=1)),
                ('employee_id', models.IntegerField(default=1)),
                ('description', models.TextField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('stock', models.IntegerField()),
                ('price', models.FloatField()),
                ('serial_num', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Order_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_date', models.DateTimeField()),
                ('authorized_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.employee')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.order')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.product')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.job'),
        ),
        migrations.CreateModel(
            name='Assembly_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finish_date', models.DateTimeField()),
                ('description', models.TextField(max_length=255)),
                ('notes', models.TextField(max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('attendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.employee')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.client')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
                ('interior_number', models.IntegerField(null=True)),
                ('exterior_number', models.IntegerField()),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('postal_code', models.IntegerField()),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.client')),
            ],
        ),
    ]
