# Generated by Django 4.0.3 on 2022-04-16 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='exterior_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='address',
            name='interior_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='contract_id',
            field=models.IntegerField(),
        ),
    ]
