# Generated by Django 4.0.3 on 2022-04-08 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_addresses_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresses',
            name='exterior_number',
            field=models.IntegerField(null=True),
        ),
    ]
