# Generated by Django 4.0.3 on 2022-04-08 02:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0003_alter_addresses_exterior_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addresses",
            name="exterior_number",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="addresses",
            name="interior_number",
            field=models.IntegerField(null=True),
        ),
    ]
