# Generated by Django 4.0.3 on 2022-04-08 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_addresses_exterior_number_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Addresses',
            new_name='Address',
        ),
        migrations.RenameModel(
            old_name='Clients',
            new_name='Client',
        ),
        migrations.RenameModel(
            old_name='Problems',
            new_name='Problem',
        ),
    ]
